name: Deploy Docs

on:
  push:
    branches: ["main"]
    paths:
      - "src/**"
      - "Cargo.toml"
      - ".cargo/**"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@nightly

      - name: Build docs
        run: cargo doc --release --no-deps --document-private-items --features spi
        env:
          RUSTDOCFLAGS: "--default-theme dark"

      - name: Add redirect index
        run: echo '<meta http-equiv="refresh" content="0; url=snled27351_driver/index.html">' > target/doc/index.html

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: target/doc

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
